#!/usr/bin/env perl

use strict; use warnings; use diagnostics; use feature qw(say);
use Getopt::Long; use Pod::Usage;

use FindBin; use lib "$FindBin::RealBin/lib";
use File::Basename qw(dirname);
use Cwd qw(abs_path);
use lib (dirname abs_path $0). "/lib";


# ==============================================================================
#
#   CAPITAN:
#   FILE:
#   LICENSE:
#   USAGE:
#   DEPENDENCIES:
#
# ==============================================================================

#-------------------------------------------------------------------------------
# VARIABLES

#-------------------------------------------------------------------------------
# COMMAND LINE
my $FILE = "";
my = "";
my = "";
my $usage = "\n\n$0 [options]\n
Options:
    -file   Input file
    -
    -
    -help   Show this message
\n";

# OPTIONS
GetOptions(
    'file=s'        =>\$FILE,
    '=s'        =>\$,
    ':s'        =>\$,
    ''      =>\,
    ''      =>\,
    help            =>sub{pod2usage($usage);}
)or pod2usage(2);

checkCLA();
#-------------------------------------------------------------------------------
# CALLS


#-------------------------------------------------------------------------------
# SUBS
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# $input = argChecks();
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# This function checks for arguments passed in command-line
# using global variables
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# $output = Dies from errors
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
sub checkCLA {
    unless ($FILE) {
        die "You did not provide an input file.", $!, $usage;
    }
    return;
}

#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# $input = ();
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# This function takes arguments
#
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# $return = ();
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
sub function_name {

}

#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# $input = ();
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# This function takes arguments
#
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# $output =
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
