#!/usr/bin/env perl

use strict; use warnings; use diagnostics; use feature qw(say);
use Getopt::Long; use Pod::Usage;

use FindBin; use lib "$FindBin::RealBin/lib";
use File::Basename qw(dirname);
use Cwd qw(abs_path);
use lib (dirname abs_path $0). "/lib";


# ==============================================================================
#
#   CAPITAN:
#   FILE:
#   LICENSE:
#   USAGE:
#   DEPENDENCIES:
#
# ==============================================================================

#-------------------------------------------------------------------------------
# GLOBALS


#-------------------------------------------------------------------------------
# COMMAND LINE
my $SCALAR;
my @ARRAY;
my $usage = "\n\n$0 [options]\n
Options:
    -scalar
    -array
    -help   Shows this message

";


# OPTIONS
GetOptions(
    'scalar'   => \$SCALAR,
    'array'   => \@ARRAY,
    help    => sub{pod2usage($usage);}
)or pod2usage(2);

checkCLA(); #check command line arguments passed
#-------------------------------------------------------------------------------
# VARIABLES


#-------------------------------------------------------------------------------
# CALLS


#-------------------------------------------------------------------------------
# SUBS
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# $input = argChecks();
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# This function checks for arguments passed in command-line
# using global variables
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# $output = Dies from errors
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
sub checkCLA {
    my () = @_;
    unless ($) {
        die "", $!, $usage;
    }
    return;
}

#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# $input = ();
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# This function takes arguments
#
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# $return = ();
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
sub function_name {
    my () = @_;


    return;
}

#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# $input = ();
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# This function takes arguments
#
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# $output =
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
sub function_name {
    my () = @_;


    return;
}
