#!/usr/bin/perl

use strict; use warnings; use diagnostics; use feature qw(say);
use Getopt::Long; use Pod::Usage;

use FindBin; use lib "$FindBin::RealBin/lib";
use File::Basename qw(dirname);
use Cwd qw(abs_path);
use lib (dirname abs_path $0). "/lib";


# =============================================================================
#
#   CAPITAN:
#   FILE:
#   LICENSE:
#   USAGE:
#   DEPENDENCIES:
#
# =============================================================================


#-------------------------------------------------------------------------
# COMMAND LINE
my $FILE = "";
my = "";
my = "";
my $usage = "\n\n $0 [options]\n
Options:
    -
\n";

# OPTIONS
GetOptions(
    'file:s'        =>\$FILE,
    ''      =>\,
    ''      =>\,
    help            =>sub{pod2usage($usage);}
)or pod2usage(2);
#-------------------------------------------------------------------------
# CALLS
argChecks();

#-------------------------------------------------------------------------
# SUBS

#---------------------------------------------------------
# $result = argChecks();
#---------------------------------------------------------
# This function checks for arguments passed in command-line
# using global variables
#---------------------------------------------------------
sub argChecks {

}

#---------------------------------------------------------
# $result = ();
#---------------------------------------------------------
# This function
#
#---------------------------------------------------------
